In [1]:
import numpy as np

In [2]:
def conv_single_step(a_slice_prev, W, b):
    s = np.multiply(a_slice_prev,W) 
    # Sum over all entries of the volume s.
    Z = np.sum(s)
    # Add bias b to Z. Cast b to a float() so that Z results in a scalar value.
    Z = Z + float(b)
    return Z

In [3]:
np.random.seed(1)
a_slice_prev = np.random.randn(3, 4, 4)
W = np.random.randn(3, 4, 4)
b = np.random.randn(1, 1, 1)

Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Z = -6.999089450680221


In [4]:
def zero_to_hero(X,pad):
    
    X_padded = np.pad(X,((0,0),(0,0),(pad,pad),(pad,pad)),'constant',constant_values = 0)
    
    return X_padded  

In [5]:
def convolution_junction(image,kernel,bias,hparameters):
    
    (image_count,number_of_channels,n_H_prev,n_W_prev) = image.shape
    (n_C_prev,n_c,f,f1) = kernel.shape
    
    stride = hparameters['stride']
    pad = hparameters['pad']
    
    X_pad = zero_to_hero(image,pad)
    
    output_height = int(np.floor(((n_H_prev+ (2*pad)-f)/stride) + 1))
    output_width = int(np.floor(((n_W_prev+ (2*pad)-f)/stride) + 1))
    
    result = np.zeros(shape=(image_count,n_c,output_height,output_width))
    
    for t in range(0,image_count):
        
        a_prev_image = X_pad[t]
        
        for y in range(0,output_height):
            
                for z in range(0,output_width):
                    
                    for m in range(0,n_c):
                        
                        vert_start = y*stride
                        vert_end = vert_start+f
                        horiz_start = z*stride
                        horiz_end = horiz_start+f
                        
                        
                        a_slice_prev = a_prev_image[:,vert_start:vert_end,horiz_start:horiz_end]
                        
                        result[t, m, y, z] = conv_single_step(a_slice_prev,kernel[:,m,:,:],bias[:,m,:,:])
                        
    cache = (image, kernel, bias, hparameters)
    
    return result, cache

In [6]:
np.random.seed(1)
image = np.random.randn(10,3,4,4)
kernel = np.random.randn(3,8,2,2)
b = np.random.randn(1,8,1,1)
hparameters = {"pad" : 2,
               "stride": 2}

In [7]:
result,ccc = convolution_junction(image,kernel,b,hparameters)

In [8]:
print("Kernel: ")
print(kernel[0])

#Image changes based on padding
print("Image: ")
print(image[0])

Kernel: 
[[[ 0.5154138  -1.11487105]
  [-0.76730983  0.67457071]]

 [[ 1.46089238  0.5924728 ]
  [ 1.19783084  1.70459417]]

 [[ 1.04008915 -0.91844004]
  [-0.10534471  0.63019567]]

 [[-0.4148469   0.45194604]
  [-1.57915629 -0.82862798]]

 [[ 0.52887975 -2.23708651]
  [-1.1077125  -0.01771832]]

 [[-1.71939447  0.057121  ]
  [-0.79954749 -0.2915946 ]]

 [[-0.25898285  0.1892932 ]
  [-0.56378873  0.08968641]]

 [[-0.6011568   0.55607351]
  [ 1.69380911  0.19686978]]]
Image: 
[[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
  [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
  [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
  [-0.3224172  -0.38405435  1.13376944 -1.09989127]]

 [[-0.17242821 -0.87785842  0.04221375  0.58281521]
  [-1.10061918  1.14472371  0.90159072  0.50249434]
  [ 0.90085595 -0.68372786 -0.12289023 -0.93576943]
  [-0.26788808  0.53035547 -0.69166075 -0.39675353]]

 [[-0.6871727  -0.84520564 -0.67124613 -0.0126646 ]
  [-1.11731035  0.2344157   1.65980218  0.74204

In [9]:
print(result[0])

[[[ 0.37245685  0.37245685  0.37245685  0.37245685]
  [ 0.37245685  2.59973365  0.98768122  0.37245685]
  [ 0.37245685  2.30309723  4.01690902  0.37245685]
  [ 0.37245685  0.37245685  0.37245685  0.37245685]]

 [[-0.1484898  -0.1484898  -0.1484898  -0.1484898 ]
  [-0.1484898  -0.38565284 -2.03321142 -0.1484898 ]
  [-0.1484898   0.2849724  -6.87618738 -0.1484898 ]
  [-0.1484898  -0.1484898  -0.1484898  -0.1484898 ]]

 [[-0.1834002  -0.1834002  -0.1834002  -0.1834002 ]
  [-0.1834002   3.58047259  0.20468645 -0.1834002 ]
  [-0.1834002   3.18884363  0.84495676 -0.1834002 ]
  [-0.1834002  -0.1834002  -0.1834002  -0.1834002 ]]

 [[ 1.1010002   1.1010002   1.1010002   1.1010002 ]
  [ 1.1010002  -2.26232114 -0.998566    1.1010002 ]
  [ 1.1010002  -0.14572506  0.49843178  1.1010002 ]
  [ 1.1010002   1.1010002   1.1010002   1.1010002 ]]

 [[ 0.78002714  0.78002714  0.78002714  0.78002714]
  [ 0.78002714 -3.85265702  5.0230028   0.78002714]
  [ 0.78002714  0.30031214  3.26927438  0.78002714]
  [ 

In [10]:
def pool_forward(A_prev, hparameters, mode = "max"):
    # Retrieve dimensions from the input shape
    (image_count,n_C_prev,n_H_prev, n_W_prev) = A_prev.shape
    
    # Retrieve hyperparameters from "hparameters"
    f = hparameters["f"]
    stride = hparameters["stride"]
    
    # Define the dimensions of the output
    output_height = int(np.floor(((n_H_prev - f)/stride) + 1))
    output_width = int(np.floor(((n_W_prev- f)/stride) + 1))

    # Initialize output matrix A
    pooled = np.zeros(shape=(image_count,n_C_prev,output_height,output_width))          
    
    ### START CODE HERE ###
    # loop over the channels of the output volume
    for t in range(0,image_count):
                
        for y in range(0,output_height):

            for z in range(0,output_width):
                    
                for m in range(0,n_C_prev):
                    # Find the corners of the current "slice" (≈4 lines)
                    vert_start = y * stride
                    vert_end = vert_start + f
                    horz_start = z * stride
                    horz_end = horz_start + f
                    
                    
                    # Use the corners to define the current slice on the ith training example of A_prev, channel c. (≈1 line)
                    sliced = A_prev[t,m,vert_start:vert_end,horz_start:horz_end]
                    
                    # Compute the pooling operation on the slice. Use an if statment to differentiate the modes. Use np.max/np.mean.
                    if mode == "max":
                        pooled[t,m,y,z] = np.max(sliced)
                    elif mode == 'average':
                        pooled[t,m,y,z] = np.average(sliced)
    ### END CODE HERE ###
   
    # Store the input and hparameters in "cache" for pool_backward()
    cache = (A_prev, hparameters)
    
    # Making sure your output shape is correct

    
    return pooled, cache

In [11]:
np.random.seed(1)

hparameters = {"stride" : 2, "f": 3}
A, cache1 = pool_forward(result, hparameters)
print("mode = max")
print("A =", A)
print()
A, cache2 = pool_forward(result, hparameters, mode = "average")
print("mode = average")
print("A =", A)

mode = max
A = [[[[ 4.01690902]]

  [[ 0.2849724 ]]

  [[ 3.58047259]]

  [[ 1.1010002 ]]

  [[ 5.0230028 ]]

  [[ 4.45377219]]

  [[ 1.78715124]]

  [[ 4.99341857]]]


 [[[ 4.06014922]]

  [[ 3.96751481]]

  [[ 2.93476538]]

  [[ 7.16692521]]

  [[ 5.78603201]]

  [[ 2.23788424]]

  [[ 1.8731739 ]]

  [[ 3.70948049]]]


 [[[ 5.87766847]]

  [[ 1.75668731]]

  [[ 4.77911267]]

  [[ 6.23666093]]

  [[13.06299406]]

  [[ 4.70968082]]

  [[ 2.58002245]]

  [[ 2.9745791 ]]]


 [[[ 4.14292478]]

  [[ 3.73534237]]

  [[ 3.58320084]]

  [[ 5.03637195]]

  [[ 4.6076332 ]]

  [[ 0.3268895 ]]

  [[-1.1134361 ]]

  [[ 0.15787917]]]


 [[[ 4.32920215]]

  [[ 2.28326724]]

  [[ 4.12156764]]

  [[10.57307032]]

  [[ 0.78002714]]

  [[ 7.71026321]]

  [[ 1.58939344]]

  [[ 3.72284257]]]


 [[[ 8.31024853]]

  [[ 0.63135621]]

  [[ 3.01977761]]

  [[ 8.27022632]]

  [[10.1307546 ]]

  [[ 2.66585007]]

  [[ 0.42454186]]

  [[ 2.20557733]]]


 [[[ 3.99704184]]

  [[-0.1484898 ]]

  [[ 3.41076081]]

  [[

In [12]:
def conv_backward(dZ, cache):

    ### START CODE HERE ###
    # Retrieve information from "cache"
    (image, kernel, bias, hparameters) = cache
    
    # Retrieve dimensions from A_prev's shape
    (m,n_c_prev,n_h_prev, n_w_prev) = image.shape
    
    # Retrieve dimensions from W's shape
    (n_c_prev, n_c, f, f,) = kernel.shape
    
    # Retrieve information from "hparameters"
    stride = hparameters["stride"]
    pad = hparameters["pad"]
    
    # Retrieve dimensions from dZ's shape
    (m, n_c, n_h, n_w) =dZ.shape
    
    # Initialize dA_prev, dW, db with the correct shapes
    da_prev = np.zeros(shape=(m,n_c_prev,n_h_prev,n_w_prev))
    dw = np.zeros(shape=(n_c_prev,n_c,f,f))
    db = np.zeros(shape=(1,n_c,1,1))
    
    # Pad A_prev and dA_prev
    pad_aprev = zero_to_hero(da_prev,pad)
    pad_image = zero_to_hero(image,pad)
    
    # loop over the training examples
    for i in range(m):  
        # select ith training example from A_prev_pad and dA_prev_pad
        aprev_indv = pad_aprev[i]
        image_indv = pad_image[i]
        
        for h in range(n_h):
            
            for w in range(n_w):
                
                for c in range(n_c):
                    # Find the corners of the current "slice"
                    vert_start = h
                    vert_end = h + f
                    horz_start = w
                    horz_end = w + f
                    
                    # Use the corners to define the slice from a_prev_pad
                    slicer_aprev = image_indv[:,vert_start:vert_end,horz_start:horz_end]

                    # Update gradients for the window and the filter's parameters using the code formulas given above
                    aprev_indv[:,vert_start:vert_end, horz_start:horz_end] += kernel[:,c,:,:] * dZ[i, c, h, w]
                    dw[:,c,:,:] += slicer_aprev * dZ[i, c, h, w]
                    db[:,c,:,:] += dZ[i, c, h, w]
                    
        # Set the ith training example's dA_prev to the unpaded da_prev_pad (Hint: use X[pad:-pad, pad:-pad, :])
        da_prev[i,:,:,:] = aprev_indv[:,pad:-pad,pad:-pad]
    ### END CODE HERE ###
    
    # Making sure your output shape is correct
    assert(da_prev.shape == (m, n_c_prev, n_h_prev, n_w_prev))
    
    return da_prev, dw, db

In [13]:
dA, dW, db = conv_backward(result, ccc)
print("dA_mean =", np.mean(dA))
print("dW_mean =", np.mean(dW))
print("db_mean =", np.mean(db))

dA_mean = -0.08476441320895874
dW_mean = 0.08062487384409356
db_mean = 11.233185763712534


In [14]:
print(ccc)

(array([[[[ 1.62434536e+00, -6.11756414e-01, -5.28171752e-01,
          -1.07296862e+00],
         [ 8.65407629e-01, -2.30153870e+00,  1.74481176e+00,
          -7.61206901e-01],
         [ 3.19039096e-01, -2.49370375e-01,  1.46210794e+00,
          -2.06014071e+00],
         [-3.22417204e-01, -3.84054355e-01,  1.13376944e+00,
          -1.09989127e+00]],

        [[-1.72428208e-01, -8.77858418e-01,  4.22137467e-02,
           5.82815214e-01],
         [-1.10061918e+00,  1.14472371e+00,  9.01590721e-01,
           5.02494339e-01],
         [ 9.00855949e-01, -6.83727859e-01, -1.22890226e-01,
          -9.35769434e-01],
         [-2.67888080e-01,  5.30355467e-01, -6.91660752e-01,
          -3.96753527e-01]],

        [[-6.87172700e-01, -8.45205641e-01, -6.71246131e-01,
          -1.26645989e-02],
         [-1.11731035e+00,  2.34415698e-01,  1.65980218e+00,
           7.42044161e-01],
         [-1.91835552e-01, -8.87628964e-01, -7.47158294e-01,
           1.69245460e+00],
         [ 5.080

In [15]:
def mask_on(x):

    ### START CODE HERE ### (≈1 line)
    mask = (x==np.max(x))
    ### END CODE HERE ###
    
    return mask

In [16]:
np.random.seed(1)
x = np.random.randn(2,3)
mask = mask_on(x)
print('x = ', x)
print("mask = ", mask)

x =  [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
mask =  [[ True False False]
 [False False False]]


In [17]:
def distribute_value(dz, shape):
    
    ### START CODE HERE ###
    # Retrieve dimensions from shape (≈1 line)
    (n_h,n_w) = shape
    
    # Compute the value to distribute on the matrix (≈1 line)
    average = dz / (n_h*n_w)
    
    #print(average)
    # Create a matrix where every entry is the "average" value (≈1 line)
    a = np.ones(shape)*average
    ### END CODE HERE ###
    
    return a

In [18]:
a = distribute_value(2, (2,2))
print('distributed value =', a)

distributed value = [[0.5 0.5]
 [0.5 0.5]]


In [19]:
def backstroke(dA, cache, mode = "max"):

    ### START CODE HERE ###
    
    # Retrieve information from cache (≈1 line)
    (A_prev, hparameters) = cache
    
    # Retrieve hyperparameters from "hparameters" (≈2 lines)
    stride = hparameters["stride"]
    f = hparameters["f"]
    
    # Retrieve dimensions from A_prev's shape and dA's shape (≈2 lines)
    (image_count,n_C_prev,n_H_prev, n_W_prev) = A_prev.shape
    (image_count,n_c,n_h,n_w) = dA.shape
    
    # Initialize dA_prev with zeros (≈1 line)
    da_prev = np.zeros(shape=(A_prev.shape))
    
    # loop over the training examples
    for i in range(image_count):
        # select training example from A_prev (≈1 line)
        a_select = A_prev[i]
        
        for h in range(n_h):
            
            for w in range(n_w):
                
                for c in range(n_c):
                # loop over the channels (depth)
                    # Find the corners of the current "slice" (≈4 lines)
                    vert_start = h
                    vert_end = h + f
                    horz_start = w
                    horz_end = w + f
                    
                    if mode == "max":
                        # Use the corners and "c" to define the current slice from a_prev (≈1 line)
                        a_slice = a_select[c,vert_start:vert_end,horz_start:horz_end]
                        # Create the mask from a_prev_slice (≈1 line)
                        mask = mask_on(a_slice)
                        # Set dA_prev to be dA_prev + (the mask multiplied by the correct entry of dA) (≈1 line)
                        da_prev[i,c,vert_start:vert_end,horz_start:horz_end] =+ np.multiply(mask,dA[i,c,h,w])
                        
                    elif mode == "average":
                        # Get the value a from dA (≈1 line)
                        a = dA[i,c,h,w]
                        # Define the shape of the filter as fxf (≈1 line)
                        shape = (1,1)
                        # Distribute it to get the correct slice of dA_prev. i.e. Add the distributed value of da. (≈1 line)
                        da_prev[i,c,vert_start:vert_end,horz_start:horz_end] += distribute_value(a,shape)
    ### END CODE ###
    
    # Making sure your output shape is correct
    assert(da_prev.shape == A_prev.shape)

    return da_prev

In [20]:
np.random.seed(1)
A_prev = np.random.randn(5, 5, 3, 2)
hparameters = {"stride" : 1, "f": 2}
A, cache = pool_forward(A_prev, hparameters)
dA = np.random.randn(5, 4, 2, 2)

dA_prev = backstroke(dA, cache1, mode = "max")
print("mode = max")
print('mean of dA = ', np.mean(dA))
print('dA_prev[1,1] = ', dA_prev[1,1])  
print()
dA_prev = backstroke(dA, cache, mode = "average")
print("mode = average")
print('mean of dA = ', np.mean(dA))
print('dA_prev[1,1] = ', dA_prev[1,1]) 

mode = max
mean of dA =  0.14571390272918056
dA_prev[1,1] =  [[-0.          0.          0.          0.        ]
 [ 0.         -0.         -0.         -0.        ]
 [ 0.         -0.24863478 -0.         -0.        ]
 [ 0.         -0.         -0.         -0.        ]]

mode = average
mean of dA =  0.14571390272918056
dA_prev[1,1] =  [[-0.64691669  0.2545702 ]
 [ 1.88140902  2.53426113]
 [ 2.52832571  2.27969093]]


In [21]:
print(dA)

[[[[-0.31011677 -2.43483776]
   [ 1.0388246   2.18697965]]

  [[ 0.44136444 -0.10015523]
   [-0.13644474 -0.11905419]]

  [[ 0.01740941 -1.12201873]
   [-0.51709446 -0.99702683]]

  [[ 0.24879916 -0.29664115]
   [ 0.49521132 -0.17470316]]]


 [[[ 0.98633519  0.2135339 ]
   [ 2.19069973 -1.89636092]]

  [[-0.64691669  0.90148689]
   [ 2.52832571 -0.24863478]]

  [[ 0.04366899 -0.22631424]
   [ 1.33145711 -0.28730786]]

  [[ 0.68006984 -0.3198016 ]
   [-1.27255876  0.31354772]]]


 [[[ 0.50318481  1.29322588]
   [-0.11044703 -0.61736206]]

  [[ 0.5627611   0.24073709]
   [ 0.28066508 -0.0731127 ]]

  [[ 1.16033857  0.36949272]
   [ 1.90465871  1.1110567 ]]

  [[ 0.6590498  -1.62743834]
   [ 0.60231928  0.4202822 ]]]


 [[[ 0.81095167  1.04444209]
   [-0.40087819  0.82400562]]

  [[-0.56230543  1.95487808]
   [-1.33195167 -1.76068856]]

  [[-1.65072127 -0.89055558]
   [-1.1191154   1.9560789 ]]

  [[-0.3264995  -1.34267579]
   [ 1.11438298 -0.58652394]]]


 [[[-1.23685338  0.87583893]
   