In [1]:
import numpy as np

image = np.random.rand(3,3,4,4)
kernel = np.random.rand(3,3,3)

In [2]:
print("Kernel: ")
print(kernel[0])

print("Image: ")
print(image[0][0])

Kernel: 
[[0.76562483 0.725774   0.85263973]
 [0.97683008 0.56384334 0.3293747 ]
 [0.29443685 0.21340599 0.39419404]]
Image: 
[[0.1117154  0.70566447 0.45545295 0.80684282]
 [0.3395883  0.73783021 0.5392052  0.54027606]
 [0.10839424 0.20519848 0.33479745 0.62357186]
 [0.11352214 0.44364134 0.87521644 0.63579373]]


In [3]:
def convolution_junction(image,kernel,padding=0,stride=1):
    
    image_count = int(image.shape[0])
    number_of_channels = int(image.shape[1])
    image_size = int(image.shape[2])
    kernel_size = int(kernel.shape[2])
    
    X_pad = np.pad(image,((0,0),(0,0),(padding,padding),(padding,padding)),'constant',constant_values = 0)
    
    print("Padded: ")
    print(X_pad[0][0])
    
    output_size = int(np.round((image_size+ (2*padding)-kernel_size/stride) + 1))
    result = np.zeros(shape=(image_count,number_of_channels,output_size,output_size))
    
    for t in range(0,image_count):
        for m in range(0,number_of_channels):
            for y in range(0,output_size):
                for z in range(0,output_size):
                    result[t][m][y,z] = np.sum(np.dot(X_pad[t][m][y:y+kernel_size,z:z+kernel_size],kernel[m]))
                    
    print("Result: ")
    print(result[0][0])
    
    return result

In [4]:
padding = 1
result = convolution_junction(image,kernel,padding)

Padded: 
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.1117154  0.70566447 0.45545295 0.80684282 0.        ]
 [0.         0.3395883  0.73783021 0.5392052  0.54027606 0.        ]
 [0.         0.10839424 0.20519848 0.33479745 0.62357186 0.        ]
 [0.         0.11352214 0.44364134 0.87521644 0.63579373 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
Result: 
[[2.14604506 4.6544961  6.4588167  4.8506942 ]
 [2.5338441  5.59430707 8.12838203 6.80158173]
 [2.30086827 5.48718844 8.14487507 7.46565352]
 [1.00027176 2.82501941 4.919684   5.1913935 ]]
