In [51]:
import numpy as np

In [52]:
image = np.random.rand(3,7,7)

In [53]:
print(image)

[[[0.62411742 0.626083   0.42116011 0.42503214 0.26727377 0.12777667
   0.80485684]
  [0.63067079 0.76735248 0.9330596  0.20863278 0.71957768 0.44756473
   0.23847055]
  [0.48617168 0.9297766  0.02326401 0.8896711  0.50970194 0.39622881
   0.26949193]
  [0.67920319 0.48765865 0.92619293 0.89590638 0.17031979 0.31444749
   0.83138553]
  [0.57999484 0.91167801 0.49519409 0.45245798 0.6303237  0.77693557
   0.63832268]
  [0.70516248 0.40592427 0.00135915 0.31519491 0.96642167 0.61603295
   0.02417504]
  [0.18546401 0.39218112 0.74135197 0.09350045 0.93721511 0.21533099
   0.49113632]]

 [[0.91272213 0.90191636 0.2722098  0.28604129 0.99104673 0.24264911
   0.19910855]
  [0.70500997 0.33493907 0.50926957 0.80814201 0.44442321 0.21863892
   0.66755659]
  [0.26345413 0.1809423  0.97048214 0.08810834 0.39687992 0.93404882
   0.33963889]
  [0.61875849 0.03890012 0.94847243 0.4124823  0.00144213 0.1193465
   0.67715201]
  [0.10079375 0.47341879 0.53452674 0.40118696 0.37362724 0.3126485
   0.41

In [54]:
kernel = np.random.rand(3,3,3)

In [55]:
print(kernel)

[[[2.83166714e-01 5.21114519e-01 2.64311071e-01]
  [3.41582041e-01 9.05472307e-01 5.23267778e-04]
  [3.10195374e-01 1.18073398e-01 8.11202776e-01]]

 [[9.60485324e-01 3.15369026e-01 1.73393002e-01]
  [9.27434847e-01 3.47215914e-01 7.72139799e-02]
  [8.84670771e-01 8.76213273e-01 3.61921982e-02]]

 [[5.26346466e-01 9.25599799e-01 6.58646043e-01]
  [5.54984097e-01 6.38407254e-01 8.48515257e-01]
  [1.30764030e-01 1.50994478e-02 3.76776571e-01]]]


In [56]:
output_size = 7-4+1
result = np.zeros(shape=(3,4,4))
number_of_channels = 3
print(result)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [57]:
for x in range(0,number_of_channels):
    z = 0
    for y in range(0,output_size):
        for z in range(0,output_size):
            result[x][y,z] = np.sum(np.dot(image[x][y:y+3,y:y+3], kernel))


In [58]:
print(result)

[[[23.74347567 23.74347567 23.74347567 23.74347567]
  [25.94732645 25.94732645 25.94732645 25.94732645]
  [21.73773803 21.73773803 21.73773803 21.73773803]
  [21.97825123 21.97825123 21.97825123 21.97825123]]

 [[21.52299655 21.52299655 21.52299655 21.52299655]
  [18.49602927 18.49602927 18.49602927 18.49602927]
  [18.28874839 18.28874839 18.28874839 18.28874839]
  [11.81109158 11.81109158 11.81109158 11.81109158]]

 [[21.8366712  21.8366712  21.8366712  21.8366712 ]
  [20.69672678 20.69672678 20.69672678 20.69672678]
  [16.101967   16.101967   16.101967   16.101967  ]
  [17.81757778 17.81757778 17.81757778 17.81757778]]]
