In [58]:
import numpy as np

In [59]:
image = np.random.rand(3,7,7)

In [60]:
print(image)

[[[0.02317284 0.16647468 0.79355417 0.96762107 0.49834373 0.43469075
   0.12763902]
  [0.68667766 0.4486529  0.16732896 0.15589897 0.21726017 0.85546166
   0.82704823]
  [0.68140969 0.32369664 0.07890526 0.48928503 0.41884335 0.46669741
   0.08213087]
  [0.99578323 0.98829801 0.78094185 0.42710261 0.22887944 0.33172617
   0.22059496]
  [0.98766826 0.34923388 0.75132494 0.26911632 0.57847497 0.16404043
   0.86454873]
  [0.62567499 0.84278267 0.23501912 0.4610119  0.72453094 0.34893905
   0.07419097]
  [0.37560368 0.40747649 0.96352638 0.23925332 0.33169217 0.27707525
   0.41740293]]

 [[0.64950541 0.57510523 0.04098587 0.37769987 0.43202579 0.74233617
   0.98621105]
  [0.3490269  0.83788561 0.86221319 0.80418064 0.08055196 0.21789044
   0.18687134]
  [0.76231058 0.01374095 0.19690814 0.71605297 0.25954422 0.29701973
   0.09171494]
  [0.63145938 0.70720295 0.72928204 0.65603837 0.24340617 0.7696454
   0.24656075]
  [0.95725776 0.08559716 0.58183453 0.85346547 0.33691925 0.32227496
   0.6

In [61]:
kernel = np.random.rand(3,3,3)

In [62]:
print(kernel)

[[[0.96487753 0.28011247 0.36038651]
  [0.5038262  0.9185465  0.07944522]
  [0.74649752 0.66406655 0.85152398]]

 [[0.04452175 0.75243613 0.64461294]
  [0.033088   0.43781041 0.07141445]
  [0.65163642 0.85748044 0.28412241]]

 [[0.21434177 0.97851895 0.7001948 ]
  [0.54021996 0.10831429 0.57921535]
  [0.56899766 0.70904193 0.94077891]]]


In [63]:
output_size = 7-4+1
result = np.zeros(shape=(3,4,4))
number_of_channels = 3
print(result)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [64]:
for x in range(0,number_of_channels):
    z = 0
    for y in range(0,output_size):
        for z in range(0,output_size):
            result[x][y,z] = np.sum(np.dot(image[x][y:y+3,y:y+3], kernel))

In [65]:
print(result)

[[[16.46833378 16.46833378 16.46833378 16.46833378]
  [18.7860837  18.7860837  18.7860837  18.7860837 ]
  [19.53136516 19.53136516 19.53136516 19.53136516]
  [16.02867558 16.02867558 16.02867558 16.02867558]]

 [[20.26889766 20.26889766 20.26889766 20.26889766]
  [27.20631186 27.20631186 27.20631186 27.20631186]
  [20.00086665 20.00086665 20.00086665 20.00086665]
  [19.74751657 19.74751657 19.74751657 19.74751657]]

 [[16.34253931 16.34253931 16.34253931 16.34253931]
  [19.03878059 19.03878059 19.03878059 19.03878059]
  [21.85419656 21.85419656 21.85419656 21.85419656]
  [24.40209695 24.40209695 24.40209695 24.40209695]]]


In [66]:
def convolution_junction(image,kernel,padding=0,stride=1,number_of_channels=3):
    image_size = int(len(image[0]))
    kernel_size = int(len(kernel[0]))

    output_size = image_size-kernel_size
    result = np.zeros(shape=(3,output_size,output_size))
    
    for x in range(0,number_of_channels):
        z = 0
        for y in range(0,output_size):
            for z in range(0,output_size):
                result[x][y,z] = np.sum(np.dot(image[x][y:y+kernel_size,y:y+kernel_size], kernel))
    return result

In [67]:
returnv = convolution_junction(image,kernel)
returnv

array([[[16.46833378, 16.46833378, 16.46833378, 16.46833378],
        [18.7860837 , 18.7860837 , 18.7860837 , 18.7860837 ],
        [19.53136516, 19.53136516, 19.53136516, 19.53136516],
        [16.02867558, 16.02867558, 16.02867558, 16.02867558]],

       [[20.26889766, 20.26889766, 20.26889766, 20.26889766],
        [27.20631186, 27.20631186, 27.20631186, 27.20631186],
        [20.00086665, 20.00086665, 20.00086665, 20.00086665],
        [19.74751657, 19.74751657, 19.74751657, 19.74751657]],

       [[16.34253931, 16.34253931, 16.34253931, 16.34253931],
        [19.03878059, 19.03878059, 19.03878059, 19.03878059],
        [21.85419656, 21.85419656, 21.85419656, 21.85419656],
        [24.40209695, 24.40209695, 24.40209695, 24.40209695]]])